### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by winternet-studio** [scott-vincent/instrument-panel#1]
How do you install and use this (on Windows)? I don't know how to compile C++, could you make .exe releases?

**Comment by scott-vincent** [comment]
I'm still working on some parts but it is definitely useable now so I will create a windows release for you. The code will also compile on a Raspberry Pi.

**Comment by winternet-studio** [comment]
Thanks!! Now running the link on the FS20 computer and it says listening on port 52020, connected to the sim, and then waiting the panel to connect. So I start up the panel on my other computer but it just says "No data link" - and "not connected" just below, hardly visible. So they are not finding each other - is there anything I can do to help it finding the server (port, IP...)? How is it suppose to discover the server? The firewall is already disabled on both computers...

**Comment by scott-vincent** [comment]
The instrument panel needs to know the IP address where data link is running. It gets this from its settings file so just change the address of the host in the settings file and restart the instrument panel. You should see the settings file when you unzip the release.

**Comment by scott-vincent** [comment]
Note that you can run as many instrument panels as you wish (on different machines). They all connect to the same data link. Also, the instruments are dimmed until the panel connects and you start a flight. I did this to save the screen (screensaver) so the instruments are only bright when you are in a mission.

**Comment by winternet-studio** [comment]
Oh! Then it works, thanks! (a quick little getting started guide would be helpful for others I think)

**Comment by scott-vincent** [comment]
Sure, still a work in progress. I need to add 4 or 5 more instruments which just have placeholders currently as you can see. At the moment I'm working on the Raspberry Pi hardware so that knobs can be used to control each instrument which adds a large amount of realism. I will add a getting started guide to my todo list.

**Comment by winternet-studio** [comment]
That's awesome. Thanks so far. No thoughts of integrating with FSUIPC?

**Comment by scott-vincent** [comment]
Glad you like it. I'm pleased with it so far and still busy creating a plywood overlay for my monitor. I'll add some pictures once its in a more finished state. As for FSUIPC, that is redundant and just an unnecessary layer as I prefer to talk to Microsoft's SDK directly and use my own optimised network code, and it's not open source. Why would you want to pay for it ;-) I have a donate button but nobody is under any obligation to pay a penny. If people don't have spare cash then I don't want to deny them any joy they may gain from using something I've created.

**Comment by scott-vincent** [comment]
ToDo: Getting started guide

**Comment by winternet-studio** [comment]
Right, if you have all you need through SimConnect there is of course no reason to throw FSUIPC into the mix. :) Thanks again.

**Comment by alexandergrib** [comment]
> I'm still working on some parts but it is definitely usable now so I will create a windows release for you. The code will also compile on a Raspberry Pi.

Would be great if you can make it windowed, because it opens at the same monitor as the game.

**Comment by scott-vincent** [comment]
Did you try pressing M to switch it to a different monitor?

**Comment by alexandergrib** [comment]
> Did you try pressing M to switch it to a different monitor?

great, it worked.

Im trying to figure out how to install and run it on raspi or ubuntu, is there manual somwhere, there is not much info here on github.

Thanks. Great program you created.

**Comment by scott-vincent** [comment]
I've added Quick Start instructions now.

**Comment by tmkdev** [comment]
Just tried it on a clean build of Raspian and a Pi 4. I too am getting the blank screen with 1.3.3. There a fix coming in the next build or should this issue be reopened?

**Comment by scott-vincent** [comment]
It's not the build that's the problem as it works fine on my Rapsberry Pi 4. It's to do with the way Allegro5 works and the way OpenGL is configured on the Pi. The problem is I don't want to trash my setup to work out exactly how the Pi should be configured, I'm hoping somebody else can get it working and document the necessary steps. Have you tried the fix to remove the reference to OpenGL ES 3 in the code? Just comment out the line that configures Allegro5.

**Comment by tmkdev** [comment]
I checked out 1.3.3 and built that with this for the OpenGL option line.

    al_set_new_display_flags(flags );

Works fine on my Pi 4 now. How do I adjust dimming?

**Comment by scott-vincent** [comment]
To stop the dimming just edit bitmaps/dim.png and make it white instead of grey ;-)

**Comment by scott-vincent** [comment]
Will re-open this issue as it may help others with the same problem.

**Comment by alexandergrib** [comment]
You dont need to trash your setup, you can pop out sd card, and put a new
one in with fresh raspbian.
