### ISSUE TITLE
HDG not working

### ISSUE THREAD

**Issue by kkr0kk** [scott-vincent/instrument-panel#11]
When you move HDG on the game, is not moving on instrument-panel (v 1.3.3 and 1.3.4)

**Comment by kkr0kk** [comment]
Find it -> hi.cpp line 143 replace to :
bugAngle = (simVars->autopilotHeading - simVars->hiHeading) * DegreesToRadians;

**Comment by scott-vincent** [comment]
Thanks for pointing it out. I've fixed it now.
