### ISSUE TITLE
Running on the Pi

### ISSUE THREAD

**Issue by mkeefe** [scott-vincent/instrument-panel#13]
I have tried to build the project and place it on the pi, however when I try to install Allegro5 for Pi or even a basic linux install, the app doesn't see Allegro5. I get the same warnings and no display.

When I do a basic Allegro example that runs.

Can you please expand on the install process to get this working?

**Comment by scott-vincent** [comment]
Not sure what you mean by build it and place it on the Pi. Try building it on the Pi you are going to run it on and use the Allegro that is installed on that same Pi.

**Comment by mkeefe** [comment]
I did a horrible job of explaining that! Let's try again:

When trying to run the instrument panel on the Pi (after installing allegro5) I am met with an error message of Allegro5 not found or valid. I could screenshot if that helps.

I was hoping for a setup guide that would kind of cover the full install process. I noticed you mentioned a standard Allegro5 install but even doing that I get errors and/or no display. I am sure its something i'm missing and hoping you could provide that additional context.

On that note, when running on another PC its amazing and really helps me try out different flight maneuvers while enrolled in flight school. So, thank you!

**Comment by scott-vincent** [comment]
Try building the code yourself on the Pi and it may become apparent what the problem is. To build it you just need to run make.sh and it will compile and link against it's dependencies, e.g. Allegro5 as long as it can find them. Try Googling for Shared Libraries to understand how they work on Linux. Usually there is an install stage so for Allegro5 you would run something like: sudo make install. This would copy the Allegro5 shared libraries to a common location, e.g. /usr/share/lib so that other programs can find them when they run.

**Comment by mkeefe** [comment]
Was able get the program to run, working out how exactly. I'll update the ticket when I have it.

**Comment by mkeefe** [comment]
Okay, here is more details on what I did.

Fresh install of Raspbian

```
sudo apt-get update
sudo apt-get upgrade
cd ~/Desktop
mkdir flight

sudo apt-get install cmake
sudo apt-get install liballegro5-dev
git clone https://github.com/scott-vincent/instrument-panel.git
cd instrument-panel/
bash make.sh

// possibly needed, depends on if allegro5 fails
sudo apt-get install mesa-utils
sudo apt-get install libgl1-mesa-dev
sudo apt-get install libxcursor-dev
sudo apt-get install libglu1-mesa-dev
```

Once everything is compiled and error-free, I simply run

`bash run.sh` in the instrument panel directory

However i'll get a black screen. 

So I close the app and swap that OpenGL bool to false and comment out that OpenGL3 line referenced in the other issue inside the instrument-panel.cpp file. Re-compile and then re-run the app.

The app now opens, but in windowed mode. Not sure how to solve that issue, but also don't want to open a new issue unless you think it'll help?

Lastly, there is a byte mismatch #14 when running, not really sure where or how it occurs, hopefully you know as i'm so close to being able to run this cool util! Thank you!

**Comment by scott-vincent** [comment]
Thanks for doing this, it's yet another thing I've been wanting to do but haven't had time. I didn't start with a clean install of Raspbian originally and I was playing with OpenGL before I started writing instrument-panel so I wasn't sure what I'd installed beforehand. This is exactly what we need, some clear instructions on how to get up and running on the Pi from a clean (known) state.

**Comment by mkeefe** [comment]
Happy to help! 99% of the way there (like all dev).

The only way I can run the app is in windowed mode (commenting out that link in `instrument-panel.cpp`) however this results in the app being much too large for a 1080p monitor, in width. Hopefully we can figure out the cause of it not being able to run in full screen and/or a way to conform the view to the display size.

**Comment by mkeefe** [comment]
Got it running, and wrote up a clean guide. Literally purchased a 2nd Pi 4 today at MicroCenter.


Step 1: Update your Raspberry Pi

```
sudo apt-get update
sudo apt-get upgrade
```

Step 2: Install Allegro5

```
sudo apt-get install liballegro5-dev
```

Step 3: Download instrument panel

```
cd ~/Desktop
mkdir flight
cd flight
git clone -b v1.3.5 https://github.com/scott-vincent/instrument-panel.git .
cd instrument-panel
```

Step 4: Config instrument panel

Open `instrument-panel/instrument-panel.cpp`

Change this line otherwise you'll only see a black screen when running the app.

`const bool UseOpenGL_ES3 = true;` to `const bool UseOpenGL_ES3 = false;`

Step 5: Build

```
./make.sh
```

Edit `instrument-panel/settings/instrument-panel.json` and set the host IP Address

Step 6: Run!

```
./run.sh
```

**Note:** You may need to change the graphics memory on your Pi, I noticed some slow redraw in a couple of occasions. However this is unconfirmed as I also suspect it could be my network as the entire world is online right now in my house!

Hope this helps someone!

Matt

**Comment by scott-vincent** [comment]
Great, at least people will know how to get up and running on the Pi 4 now. The only caveat is I suspect this method won't be taking advantage of hardware accelerated OpenGL on the Pi but if it's fast enough then that's fine. It's a bit fiddly getting OpenGL ES3 working, I think that's when you need to start messing around changing boot options and maybe installing Mesa libraries. As I say, I will sit down one day and work it out properly.

Thanks for your helpful instructions.

**Comment by emxsys** [comment]
@mkeefe, I received my Pi4 yesterday and straight away I used your "clean guide" instructions to setup my instrument panel.  They were flawless. The only change I made was to use v1.3.6. Thanks!!

I too had a problem with latency on my wireless network. Not only a slow refresh, but frequent "NO DATA LINK" messages, screen flash, and disappearing gauges.  So I setup a peer-to-peer Ethernet connection between the Pi and the desktop computer with a crossover cable.  I was happy to see the _instrument-data-link_ program connect on the second network. :+1:  Problem resolved! It's been working flawlessly.  Thanks @scott-vincent !!

Perhaps the "clean guide" and subsequent instructions could go into the project's wiki.

**Comment by mkeefe** [comment]
@emxsys Thanks! Thank you also for the insight on the peer-to-peer network, i'm going to give that a try.

**Comment by emxsys** [comment]
@mkeefe I hope you were able resolve the networking issues.  I case you (or someone else for that matter) are having problems here's a tip from my experience:

Initially the **instrument-data-link** program on Windows would not detect the **instrument-panel** running on the Pi. Windows categorized the peer-to-peer network as a _Guest_ or _Public_ network, so I had to change the firewall permissions for the **instrument-data-link** program to allow _Public_ network access.

**Comment by bleckett** [comment]
Hi guys... followed @mkeefe 's process on a clean Pi4 as well (thank you) and currently going through WiFi until I can find a cable to hook up peer-to-peer. But I'm getting a crash right after a connection is established. '**line 2:11761 Segmentation fault ./instrument-panel**'. I'm also seeing '**Datalink: Requested 1136 bytes but server has 1152**' 

I didn't want to file a bug yet as it may be something happening on my end? 
I'm using version 1.4.0 Any thoughts?

**Comment by emxsys** [comment]
@bleckett I'm pretty sure the errors means the Datalink version and Instrument Panel version are out of sync.

Just a hunch, in the context of v1.4 and @mkeefe's instructions, did you change the version number to v1.4.0 in the following command:
```
git clone -b v1.3.5 https://github.com/scott-vincent/instrument-panel.git .
```
If you downloaded DataLink v1.4.0 and you cloned v1.3.5 then the two versions are out of sync. You'll want to clone v1.4.0

**Comment by bleckett** [comment]
I agree. I'm going to go through it more tonight. I cloned with out the build switch so it's the most recent version (which is less than 24 hours old). But I didn't see a build/version number on the data-link, though it could be an older version. Thanks.

**Comment by scott-vincent** [comment]
I double checked the work I did yesterday and I did forget a commit but it was only the data-link version nmber (which may cause a little confusion). I've added it now but that obviously won't be fetched with tag v1.4.0. The problems you are seeing are defintely mismatched versions but v1.4.0 looks good to me so I think if you just retrace your steps and grab the latest versions/code again it should work for you. Each variable is 8 bytes (double) so one of your simvarDefs.cpp files (either panel or data-link) has 2 variables missing, Both files should always be identical. The recent change to remove banking assist removed two variables I think so its your data-link that is not up-to-date. Just clone the latest code without a tag.

**Comment by bleckett** [comment]
Hey Scott - Thanks. All is good with 1.4.0 Works like a charm.

**Comment by creaimmo** [comment]
Bonjour, je suis sur une version Raspberry pi os (64bit) du coup il m'est impossible d'exécuter la version pi os. Prévoyez vous de faire une version 64bit ? cordialement

**Comment by scott-vincent** [comment]
No plans to support Rapsberry Pi OS 64-bit version currently because last time I looked it was still in Beta and was rather lacking (no hardware acceleration). When they work on it further and release a proper version then I will consider supporting it.

**Comment by creaimmo** [comment]
Hello, I contact you because I have this error message that appears 

`datalink : requested 920 bytes but server has 896 bytes v1.5.0`

and I would like to know or I can change it to make it work

**Comment by creaimmo** [comment]
finally I managed to solve my problem by recompiling the whole

**Comment by scott-vincent** [comment]
Make sure your version numbers match. So if you are running v1.5.0 of data link then you must use v1.5.0 of instrument-panel.

**Comment by fweinrebe** [comment]
Tested with v1.53 and it also works well. 
@scott-vincent it would be nice if you can put the steps in the README.md file please, then it will be easier to find.

Here are Matt's @mkeefe steps from above, but I just added a line that is missing in Step 5:

**Step 1: Update your Raspberry Pi**

sudo apt-get update
sudo apt-get upgrade

**Step 2: Install Allegro5**

sudo apt-get install liballegro5-dev

**Step 3: Download instrument panel**

cd ~/Desktop
mkdir flight
cd flight
git clone -b v1.5.3 https://github.com/scott-vincent/instrument-panel.git .
cd instrument-panel

**Step 4: Config instrument panel**

Open _instrument-panel/instrument-panel.cpp_

Change this line otherwise, you'll only see a black screen when running the app.

Change:
const bool UseOpenGL_ES3 = true; 
    to 
const bool UseOpenGL_ES3 = false;

**Step 5: Build**

cd ..
./make.sh

**Step 6: Run!**

Edit instrument-panel/settings/instrument-panel.json and set the host IP Address
./run.sh

**Comment by scott-vincent** [comment]
New section "Quick Start on Raspberry Pi" added to readme. It is a lot simpler now.
