### ISSUE TITLE
DataLink: Requested 1088 bytes but server has 1064 bytes

### ISSUE THREAD

**Issue by mkeefe** [scott-vincent/instrument-panel#14]
Got the program to run on the PC host and the Raspberry Pi 4. Yay!

However, when I run FS 2020 and have the link and pi program running I see this error and then the panel stops responding:

"DataLink: Requested 1088 bytes but server has 1064 bytes"

I do have debug mode set but no other relevant info shown, other than the final line of "Exiting". Which makes the PC application state: "Waiting for instrument panel to connect"

**Comment by pfrench42** [comment]
Those errors are typically there when the SimVars aren't the same on the windows box and the pi.  There's a data size mismatch.

To get them to work together, I update data-link and instrument-panel and compile them both.

**Comment by mkeefe** [comment]
> Those errors are typically there when the SimVars aren't the same on the windows box and the pi. There's a data size mismatch.
> 
> To get them to work together, I update data-link and instrument-panel and compile them both.

@pfrench42 Appreciate that. Do you have a quick overview of how to build on the PC?

**Comment by scott-vincent** [comment]
Yes, that's correct. If there are commits after the latest release then the pre-built version of SimVars may not be in sync with the up-to-date version that you are building. You can either compile both instrument-panel and data-link so you get the up-to-date version of both or alternatively, fetch the instrument-panel source for the Pi using the GitHub tag that matches the pre-built version. The source is always tagged when there is a new release.

When I get around to it I will produce new releases with all the latest changes so you won't have this problem for long.

**Comment by mkeefe** [comment]
Compiling the same version tag worked! Closing.
