### ISSUE TITLE
Add ILS Approach behavior to VOR

### ISSUE THREAD

**Issue by emxsys** [scott-vincent/instrument-panel#17]
The VOR CDI behavior requires more sensitivity/precision when doing an ILS approach.  When tuned to a localizer the needle deflection should be ~3-4 degrees left or right instead of the 10 degrees used when tuned to a VOR.

The relevant simulation variables needed to implement the desired behavior include:

- NAV HAS LOCALIZER: bool
- NAV LOCALIZER: degrees

And possibly, but not anticipated:
- NAV BACK COURSE FLAGS
- NAV CODES

**Comment by scott-vincent** [comment]
Added:
simVars->navHasLocalizer
simVars->navLocalizer
