### ISSUE TITLE
Display GPS cross track error on VOR

### ISSUE THREAD

**Issue by emxsys** [scott-vincent/instrument-panel#18]
When the GPS controls NAV1 the GPS cross track error should be displayed on the VOR's CDI.

To implement the desired behavior, the relevant simulation variables needed include:

- GPS DRIVES NAV1: bool
- GPS WP CROSS TRK:  meters

Other related variables, but not anticipated for this specific feature, include:

- GPS APPROACH APPROACH TYPE

**Comment by scott-vincent** [comment]
Added:
simVars->gpsDrivesNav1
simVars->gpsWpCrossTrk

**Comment by scott-vincent** [comment]
If you need to debug and want to display the value of a variable during a flight in any instrument panel code you can do, e.g:

sprintf(globals.error, "crossTrk: %f", simVars->gpsWpCrossTrk);

and the output will appear on the Annunciator.

**Comment by emxsys** [comment]
Thanks!
Where can I find `SimConnect.h`?

**Comment by emxsys** [comment]
Re: SimConnect.  Nevermind. I found the MSFS SDK. 
```
[DevMode] Help > SDK Installer
```

**Comment by scott-vincent** [comment]
Yes, that's the one.

**Comment by emxsys** [comment]
@scott-vincent We need to think about how to indicate when the GPS drives NAV1.  FS2020 has a more modern VOR instrument which illuminates the GPS and NAV flags.  To replicate the sim instrument's behavior we need to be able to show both GPS and NAV at the same time (for when GPS controls NAV1 and NAV1 is tuned to a  VOR).  How would you like to indicate this?

Ideas:
- GPS text toggled on/off
- static GPS text with barber pole

**Comment by emxsys** [comment]
@scott-vincent Here's another idea:

- Add "GPS" to the collection of barber pole and TO/FROM flags.  When the GPS is active the TO/FROM indicators are irrelevant. 

I really like this idea, even though it can't indicate a tuned VOR and GPS at the same time, it maintains the mechanical feel of the instrument.
