### ISSUE TITLE
Raspberry Pi 4 Blank Black Screen

### ISSUE THREAD

**Issue by coopermor** [scott-vincent/instrument-panel#2]
I have instrument-data-link running on the host computer. It is working because running your compiled binary for instrument-panel for Windows on the host computer is working.

On a Raspberry Pi 4 I built and ran the software using: 
```
git clone https://github.com/liballeg/allegro5.git
git clone https://github.com/scott-vincent/instrument-panel.git
mkdir allegro5/build
cd allegro5/build
cmake .. -DCMAKE_BUILD_TYPE=Release
make && sudo make install
cd ~/instrument-panel
bash make.sh
./run.sh
```

All I get is a blank full screen black screen. Instrument-data-link shows `Instrument panel connected from 192.168.0.17` Pressing p and v show a blue box but nothing else responds. The console tells me to add knobs and switches with the pin numbers. Are these required or optional when running on a raspberry pi?

**Comment by scott-vincent** [comment]
If you don't have any hardware knobs edit intrument-panel.cpp and change line 104 to

const bool HaveHardwareKnobs = false; 

Also, if you are building instrument-panel from source you will also need to build data-link on windows from source as the two need to be kept in sync and I am still actively developing them. Once they have stabilised I will create a new release. Have you tried running the prebuilt version of intrument-panel on the Pi as this matches the prebuilt windows version.

**Comment by scott-vincent** [comment]
Also, as you are getting a black screen try changing line 106 of the same file to:

const bool Debug = true;

This will force it to run in windowed rather than full screen mode and may give you a clue why it is not working correctly.
One thing I haven't made clear is that you need to be running the Pi in desktop mode (where you log into the UI), and you then need to run a terminal session under that same user and start the program from there. Don't run the program as root.

**Comment by scott-vincent** [comment]
I've noticed I have the OpenGL driver enabled on my Raspberry Pi 4 which may be the secret sauce you need to make Allegro5 work with the options above. Run "sudo raspi-config" then go to Advanced Options -> GL Driver and select "OpenGL desktop driver with fake KMS". Reboot and then try again.

**Comment by coopermor** [comment]
I got the latest Flight Simulator patch running so I gave this another shot. I pulled the latest instrument-panel and instrument-data-link (4b364ac and 3207f9c). Building both in Visual Studio got me a running instrument panel on Windows. On raspbery pi 4 I verified I was using "OpenGL desktop driver with fake KMS" and I still had the black screen. I compiled it with Debug true and HaveHardwareKnobs false and it ran in windowed mode but still with a black screen. There were no messages in the terminal.

I also downloaded releases v.1.2.0 binaries for data-link and panel for raspberry pi. Data-link shows
````
Waiting for instrument panel to connect
Instrument panel connected from 192.168.0.17
````
But the panel on the raspberry pi is still blank.

Also is there somewhere we can chat like Discord? I'd like to contribute but I had some questions and don't want to clog up GitHub issues.

**Comment by scott-vincent** [comment]
It sounds like Allegro5 isn't working properly. Not sure if it comes with examples but get one of those running first and then instrument-panel should work. I'm not sure exactly how my Pi4 is configured so I may have done something that made it work without realising. When I get around to it I will do a clean Raspian install and work out exactly what is needed for Allegro5 to run successfully. If you want to contact me directly send a message to scottvincent at yahoo.com which is my junk email address. I will then pick it up and reply on my real email address.

**Comment by emxsys** [comment]
> Also is there somewhere we can chat like Discord? I'd like to contribute but I had some questions and don't want to clog up GitHub issues.

These issues/threads are extremely valuable. I hope you can keep them public. Thanks.

**Comment by pfrench42** [comment]
FWIW: I'm getting the same issue running this on an odroid-C4 and even desktop linux (manjaro)

I have verified the odroid-c4 port is connecting to the FS2020 computer and receiving vars updates, it's just none of the instruments are rendering on either system (black screen).  I've noticed if I press "v" I'll get a blue rectangle in the display window on both platforms though.

Also, I've built allegro5 from source on both platforms and the demos are working.

**Comment by scott-vincent** [comment]
The only thing I can think to check is the Allegro display flags. Try commenting out this line in instrument-panel.cpp or try using different flags:  al_set_new_display_flags(flags | ALLEGRO_OPENGL_3_0 | ALLEGRO_OPENGL_ES_PROFILE);

**Comment by pfrench42** [comment]
BINGO!!!  Thanks!

**Comment by alexandergrib** [comment]
> The only thing I can think to check is the Allegro display flags. Try commenting out this line in instrument-panel.cpp or try using different flags: al_set_new_display_flags(flags | ALLEGRO_OPENGL_3_0 | ALLEGRO_OPENGL_ES_PROFILE);

commenting out did not do anything.  Im getting black screen only, and blue rectangle come out when press V.
<img width="797" alt="Capture" src="https://user-images.githubusercontent.com/55490733/94939994-ccc06d80-04ca-11eb-8808-43dd313dcbc3.PNG">

Terminal output shows : 
~/instrument-panel/run.sh
/home/pi/instrument-panel/run.sh: line 1: cd: instrument-panel: Not a directory
Add knob: 27, 22
....
Add switch: 16
