### ISSUE TITLE
Learjet ADI - inverted

### ISSUE THREAD

**Issue by ericktruter** [scott-vincent/instrument-panel#24]
Hi, 

Great work, hope to see more on this projects!

Just a bug on the Learjet ADI, it is seems to be inverted, so Sim left turns appear a right and Sim up appears down on the Learjet ADI. The normal one is fine.

**Comment by scott-vincent** [comment]
Sorry about that. I don't use the Learjet ADI myself so not noticed. I'll fix it for the next release.

**Comment by ericktruter** [comment]
Thanks, also noticed I can't seem to get the "Fast" ASI working, just won't load. I tried using "ASI Fast"

**Comment by scott-vincent** [comment]
"Fast" instruments are selected auotmatically when you are in a fast plane. Just set the instrument to "ASI" in settings. If you then use a fast plane such as an airliner the instrument will automatically switch to the fast version.

**Comment by scott-vincent** [comment]
Done
