### ISSUE TITLE
Instruments Update Rate

### ISSUE THREAD

**Issue by Pontiac51** [scott-vincent/instrument-panel#25]
I apologize for contacting you this way, but I found no other means. Before running this on a Pi I thought it would be best to try it out locally. So I ran your Programm on the same PC the Flight Simulator runs and that worked instantly. 

But the update rate seems to be at 1/second and hence unusable. Is there any way I can improve on this and make the instruments more responsive? 

Thx for your work!

**Comment by scott-vincent** [comment]
Sounds like a bandwidth problem. If you are using wireless switch to wired connections instead. It is pushing quite a lot of data over the network.

**Comment by Pontiac51** [comment]
I am running the program on the same PC as the simulator. How could bandwidth be a factor?

**Comment by creaimmo** [comment]
I'm ethernet and I also find worries about update rates seems to be at 1 second and therefore difficult to use it. Is there a way I can improve on this and make the instruments more responsive?

Thx for your work!

**Comment by scott-vincent** [comment]
If you are on ethernet then your bandwidth should be fine so could be a problem with your Allegro installation. Have you checked your Pi 4 resources to see where the bottleneck could be. Start by running 'top'. My instrument panel uses around 26% cpu and 5.5% memory and is updating at around 30 fps. Then the v3d_bin and v3d_render processes use another 2.5% cpu each.

Also, make sure you have the following in /boot/config.txt

```
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2
```

**Comment by creaimmo** [comment]
```
[pi4]
 # Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
 max_framebuffers=2
```

I do have this in the file  config.txt

J'ai réalisé une vidéo si vous voulez je peux vous envoyer en MP pour vous montrez la charge du processeur et du RPI qui n'est pas élevé et la latence que j'obtiens.
