### ISSUE TITLE
Note: pullUpDnControl does not work on RasPi4 so have to use raspi-gpio command-line to pull up resistors.

### ISSUE THREAD

**Issue by cleverca22** [scott-vincent/instrument-panel#3]
for VC4, pull up/down was controlled by a weird mode and latch strobing setup, that was write only

on VC6, its a much much cleaner setup:
https://github.com/librerpi/rpi-open-firmware/blob/master/docs/gpio.txt#L54-L60
https://github.com/librerpi/lk/blob/vc4/platform/bcm28xx/gpio.c#L89-L94

its just a big flat array of 2 bits per pin, so you just read the right 32bit chunk, clear the right 2 bits, then set it to 0/1/2 based on the desired direction
another advantage over VC4, is that you can also read the current pull directions

**Comment by scott-vincent** [comment]
Ah ok. I think the problem is I'm using Gordon's WiringPi library but since the community annoyed him it is no longer maintained and is not up-to-date for the Pi 4 (unless somebody has updated it). So I'm just using the command line for now which is not an elegant solution but serves the purpose.

**Comment by cleverca22** [comment]
it should be fairly simple to just do your own GPIO and directly mmap /dev/gpiomem yourself
