### ISSUE TITLE
Attitude pitch trim compensation not being displayed

### ISSUE THREAD

**Issue by schmaxEs** [scott-vincent/instrument-panel#35]
Hi - first of all thanks for the great work! I appreciate it!
One minor thing that came to my mind is that the attitude indicator is not adapting to pitch trim compensation (lower/raise the plane compared to level).
If you turn the encoder knob in MS FS 2020 left/right the gauge is adapting accordingly - but only in the sim itself, not in your dashboard. Am I doing anything wrong or is it just not implemented/not possible to implement?
Thanks in advance!
Regards
schmax

**Comment by scott-vincent** [comment]
That adjustment is not connected to the sim as all it does is adjust for the height of the pilot but you can attach a rotary encoder to adjust it if you really want to. I've never found the need for this though as the default position is dead centre so no need to adjust. I'm sure you've found the actual pitch trim which is on the Trim/Flaps instrument. This is the only one you need to adjust and this is connected to the Sim correctly.
