### ISSUE TITLE
Complete instruction of Install instrument-panel on Pi4.

### ISSUE THREAD

**Issue by benli21** [scott-vincent/instrument-panel#39]
It looks like many people has truble to install and run the instrument panel on Pi4. I am here to help.

It took me a few days and multi experiments to work out below instruction. I am sure it will help all flight lovers to set it up. i try to make it as simple as possible even for someone who does not know Linux much. 

Get a Pi4 with fresh and latest Pi4B official image. You can download the "Raspberry Pi Imager" windows app from the offical website and downlowd the latest Image file which is about 2.8G.

Then set up your fresh imaged Pi4 with Wifi or cable network. For those who does not want to have 2 set of keyboard/mouse on table, you can set up "Barrier" on both Windows PC and Pi4 to share the keyboard and mouse between Pi4 and Windows.

Run "sudo apt-get install barrier" to install it on Pi4.

Detail insturctions for it on below Youtube link.

https://www.youtube.com/watch?v=NRNh5zsb1U8&t=2s

First of all, install all below package before install the Alegro5. 
just in case you are not a Linux person, jsut simply copy and paste those command lines in your terminal and hit Enter to run.

sudo apt-get install libgdk-pixbuf2.0-dev
sudo apt-get install libpango1.0-dev
sudo apt-get install libcairo2-dev
sudo apt-get install cmake
sudo apt-get install libx11-dev
sudo apt-get install libgl1-mesa-dev
sudo apt-get install libxcursor-dev
sudo apt-get install freeglut3-dev
sudo apt-get install libpng-dev
sudo apt-get install libjpeg-dev
sudo apt-get install libfreetype6-dev
sudo apt-get install libgtk2.0-dev
sudo apt-get install libasound2-dev
sudo apt-get install libpulse-dev
sudo apt-get install libopenal-dev
sudo apt-get install libflac-dev
sudo apt-get install libdumb1-dev
sudo apt-get install libvorbis-dev
sudo apt-get install libphysfs-dev
sudo apt-get install liballegro5-dev
sudo apt-get install libsqlite0
sudo apt-get install python-libxml2
sudo apt-get install libegl1-mesa-dev libgbm-dev libgles2-mesa-dev
sudo apt-get install mesa-utils libgl1-mesa-dev libglu-dev
sudo apt-get install libxcb-cursor-dev
sudo apt-get install libxcursor-dev
sudo apt-get install build-essential xorg-dev 

After all above packages were installed, run below line to download the Allegro5 from Github. This is the verison I used. not the latest one. But work on my Pi4-B.

wget https://github.com/liballeg/allegro5/releases/download/5.2.4.0/allegro-5.2.4.0.tar.gz

tar -zxvf allegro-5.2.4.0.tar.gz

cd allegro-5.2.4.0
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-raspberrypi.cmake
make
sudo make install
sudo ldconfig
cd ~

Now the Allegro5 should be installed on your Pi4-B withour any error.

now you can download the instrument panel with below line. There is a problem with the current (as today 27 Oct 21) latest version V1.5.3 and the lastest GitHub version if you git is directly from GitHub. It does not match the latest data-link server version. 
Your instrument-panel version on the Pi4B must be the same version as the data-link your run on the windows PC (which is the same PC you run FS2020). otherwise, the Pi4B instrument clinet will reqest a different package size to the data link server would expect, and it will not work.

So, I decide to use the V1.5.2 instead for both Data-link server on Windows and the instrument-panel on the Pi4.

wget https://github.com/scott-vincent/instrument-panel/releases/download/v1.5.2/instrument-panel-v1.5.2-raspi4.tar.gz
tar -zxvf instrument-panel-v1.5.2-raspi4.tar.gz
cd instrument-panel-v1.5.2-raspi4
./make.sh

Now, the instrument panel has installed. However, before you run it, you need to disable the OpenGL_ES3. (I do not how to set the OpenGL correctly on my Pi4, if someone know, please let me know. my email is liyingshi2008@hotmail.com).

So, set UseOpenGL_ES3 to false in "instrument-panel.cpp" as below:

const bool UseOpenGL_ES3 = false;

Set your Data-link server IP too. below is my example.

  "Data Link": {
    "Host": "192.168.0.223",
    "Port": 52020
  }

now, you are ready to run. 

First, start you data-link server on the Windows
Second, start FS2020, wait until the FS2020 fully start.... (you do not have to wait to start the instrument panel on your Pi4)
Final. start instrument panel by run  "./run.sh" in the instrument folder.

Now, you should be able to see everything is live now. 

The next step would be adjust the each instrument display size and position based on your display. I have a 13" 2K 2160x1440 portable screen just for this. you can configure the the "setting/instrument-panel.json" manually to set up each instrument size and position. 
it's much quicker than setting it in the app. below is my "setting/instrument-panel.json". but, it's only for my screen resolution. if you have some basic Math knowledge, you should be able to convert it to your resolution easily.

{
  "Data Link": {
    "Host": "192.168.0.223",
    "Port": 52020
  },
  "Monitor": {
    "StartOn": 1
  },
  "ASI": {
    "Enabled": true,
    "Position X": 450,
    "Position Y": 0,
    "Size": 430
  },
  "ADI": {
    "Enabled": true,
    "Position X": 880,
    "Position Y": 0,
    "Size": 430
  },
  "ALT": {
    "Enabled": true,
    "Position X": 1310,
    "Position Y": 0,
    "Size": 430
  },
  "VOR1": {
    "Enabled": true,
    "Position X": 1740,
    "Position Y": 0,
    "Size": 430
  },
  "TC": {
    "Enabled": true,
    "Position X": 450,
    "Position Y": 500,
    "Size": 430
  },
  "HI": {
    "Enabled": true,
    "Position X": 880,
    "Position Y": 500,
    "Size": 430
  },
  "VSI": {
    "Enabled": true,
    "Position X": 1310,
    "Position Y": 500,
    "Size": 430
  },
  "VOR2": {
    "Enabled": true,
    "Position X": 1740,
    "Position Y": 500,
    "Size": 430
  },
  "Trim Flaps": {
    "Enabled": true,
    "Position X": 880,
    "Position Y": 1000,
    "Size": 430
  },
  "RPM": {
    "Enabled": true,
    "Position X": 1310,
    "Position Y": 1000,
    "Size": 430
  },
  "ADF": {
    "Enabled": true,
    "Position X": 1740,
    "Position Y": 1000,
    "Size": 430
  },
  "Annunciator": {
    "Enabled": true,
    "Position X": 92,
    "Position Y": 5,
    "Size": 356
  },
  "Digital Clock": {
    "Enabled": true,
    "Position X": 6,
    "Position Y": -24,
    "Size": 443
  },
  "Fuel": {
    "Enabled": true,
    "Position X": 0,
    "Position Y": 430,
    "Size": 250
  },
  "EGT": {
    "Enabled": true,
    "Position X": 250,
    "Position Y": 430,
    "Size": 250
  },
  "Oil": {
    "Enabled": true,
    "Position X": 0,
    "Position Y": 680,
    "Size": 250
  },
  "VAC": {
    "Enabled": true,
    "Position X": 250,
    "Position Y": 680,
    "Size": 250
  },
  "Nav": {
    "Enabled": true,
    "Position X": -130,
    "Position Y": 1000,
    "Size": 1090
  },
  "ADI Learjet": {
    "Enabled": false
  },
  "Rad Com": {
    "Enabled": false
  },
  "ASI Savage Cub": {
    "Enabled": false
  },
  "RPM Savage Cub": {
    "Enabled": false
  },
  "COM Savage Cub": {
    "Enabled": false
  },
  "XPDR Savage Cub": {
    "Enabled": false
  }
}

Now, my next step is to work on those knobs. Good luck to me.....
![WeChat Image_20210927134703](https://user-images.githubusercontent.com/48168928/134842731-42fb4adc-355f-4ddc-93ee-22c94c1bd723.jpg)

**Comment by benli21** [comment]
Hi Scott, 

I would like to say thanks for your great work to have this app done. I wish my instruction will make it easier for more people to use it.  I tried to contact you by email before, however, the email i got must be wrong. 

would you mind to drop me a line to liyingshi2008@hotmail.com as I do have a few question too.

thanks.

Ben

**Comment by scott-vincent** [comment]
The install on Rapsberry Pi is greatly simplified now. I've added a Quick Start on Raspberry Pi section to the readme. Allegro can now be installed simply by doing "sudo apt install liballegro5-dev".
