### ISSUE TITLE
instrument panel compiled Ok, V test working on all gauges, but with MSFS needles move randomly

### ISSUE THREAD

**Issue by airmassimo** [scott-vincent/instrument-panel#45]
Hi Scott, I compiled latest version of your extraordinary code, and all went smoothly, the "V" test works perfectly, all gauges updates correctly according to the value set by left-right arrows, so all seemed Ok.
When I launch MSFS though, the needles move randomly, eg. the ADI rotates on bank angle even if the plane is still on the ground, and the airspeed doesn't move. Altimeter baro setting rotates frantically but other needles stay still. Compass rotates continuously. Only RPM seems to work perfectly. I tested the panel with the G58. The pre-compiled version works perfectly.
I attach my compiled version, just in case you would like to give it a try.
I can't find a perfect match between the data-link and the panel release number, one is 6.3, the other is 6.4 or 6.5..
[Release.zip](https://github.com/scott-vincent/instrument-panel/files/9126528/Release.zip)
My target would be to slightly modify some gauge in order to make it more similiar to the one on the airplane I'm using!

**Comment by scott-vincent** [comment]
Ah yes, sorry. The versions are out of step and I found some source I had locally that isn't in Github. Please pull the latest instrument-data-link source and rebuild, then it should all work.

Sorry about that.

**Comment by airmassimo** [comment]
YEES! Now it works perfectly, thanks a lot! 
Well, now I have a mountain to climb... but I'll start from a simple gauge (maybe the IAS) and try to create a new one changing bitmaps and the angle progression, then I'll try to do something more difficult (I would like to create a standby gauge for A320 Neo, that is a sort of little pfd). 
Just one more question : in a picture of your beautiful cockpit you have 2 gauges on the left that seem on 2 tablets, what software are they running on ? Are they driven by Raspberry or what ? And you also have a CDU/FMC on the right, I am searching things like those!

**Comment by scott-vincent** [comment]
I'm glad it's working now. Was my fault for not checking in my changes. The 2 tablets are both Android tablets. The one on the left is connected to the PC via a USB lead and acts as a 4th PC monitor by using free software called Spacedesk. I then "pop-out" the 2 instruments from the FBW A320neo (or Cessna or DA62 or whatever plane I'm flying) using the FS2020 feature where you hold down the ALT GR key on the keyboard and click on some guages in the cockpit. You can then drag the popped out instruments to another monitor so I drag it from my 3 main monitors onto the Android screen. The second tablet is just running a browser and using the excellent FBW A32NX feature to display the MCDU in the Chrome browser so it just connects over Wifi (the server part runs on the main PC and is included with the FBW A32NX download).

**Comment by airmassimo** [comment]
Thanks, I'm also using spacedesk and popup gauges. but I thought you were flying a small prop plane in that picture, not an A320! I would like to create some sort of "generic" pfd, with ADI, IAS, ALT, VSI and heading... maybe it's far too difficult for my current skills, I programmed a lot of gauges for my FSX models (XB70, G91Y, X15, B47, RA5C Vigilante, etc) but I used mostly xml.
I'm really enjoying your panel, thanks for sharing it!

**Comment by airmassimo** [comment]
Hi Vincent, I am developing your beautiful C++ code and (specially) the
graphics in order to create the gauges
for the DCDesigns Concorde.
I managed to create a good mix of gauges, that look and work quite
similarly to those on the DCD model.
I enclose some image of my home cockpit so you can see what I'm doing.
I want to thank you for sharing the source code and all the informations
needed to use it.
Please let me know what you think and if I can show some pictures of my
panels on my personal pages,
or if you want more informations or anything else.
Best regards
Massimo





Il giorno dom 17 lug 2022 alle ore 22:14 Scott Vincent <
***@***.***> ha scritto:

**Comment by scott-vincent** [comment]
Hi Massimo,

I'm gald you found it useful. I'd really like to see some pictures of your Concorde gauges if you have some available.

Thanks,
Scott

**Comment by airmassimo** [comment]
Hi Scott,
of course, here you find some pictures of the gauges, let me know if I can
send you the source code
as a zip file, so you could have a look at it.
I removed some automatic selection of the gauges in order to simplify the
code, and removed also
the raspberry knobs code (I use arduino with Mobiflight and works perfectly
for me) but it would
be easy to add these parts of code back again.
I used Xara Xtreme 5 to make accurate gauges graphics, exported to
transparent png.
Looking forward to hearing from you.
Best wishes

Massimo



Il giorno ven 2 mag 2025 alle ore 07:14 Scott Vincent <
***@***.***> ha scritto:

**Comment by scott-vincent** [comment]
Sorry, but I don't see any pictures. Did you include a link? If you attached them to the email I think Github deletes them.

**Comment by airmassimo** [comment]
Mmh... I attached the images to the email, clearly it doesn't work this way.
I can send a link to my drive, or is there other way ?
I don't know github very well (at all...)

massimo


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Privo
di virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 2 mag 2025 alle ore 08:54 Scott Vincent <
***@***.***> ha scritto:

**Comment by airmassimo** [comment]
Hi Scott,
this is the link for the source code with all images :
https://drive.google.com/file/d/1ZDIV6o-5JMiSEcIgybdVnG_deLBZyBxZ/view?usp=sharing
and for data-link
https://drive.google.com/file/d/1q3poUqpZHNakWLZ6CzQx4X_cNUGmpc2g/view?usp=sharing
please let me know your thoughts!

massimo



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Privo
di virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-4395882470605819450_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 2 mag 2025 alle ore 08:54 Scott Vincent <
***@***.***> ha scritto:

**Comment by airmassimo** [comment]
Here you can find a link with some images of my home cockpit in the
"Concorde style".
All functions and flight and aircraft data can be monitored and set by the
hardware, the main monitor only displays the view from the windshield.
https://drive.google.com/file/d/1EnWsdFoxGa9hNAd4VM17HBbbaKMtUDIL/view?usp=sharing

massimo




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Privo
di virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 2 mag 2025 alle ore 08:54 Scott Vincent <
***@***.***> ha scritto:

**Comment by scott-vincent** [comment]
Wow, looks great.

**Comment by airmassimo** [comment]
Thanks Scott,
it's all due to your excellent software that allowed me to simply
change the graphics and modify the coordinates and angles of
rotation of the needles.
I think that adding more panels configurations and graphics
would add a lot of interest to your beautiful project.
I studied also the original Learjet project but your version
is much more complete and efficient.
I don't know if it's better to make specific folders and code
for each panel or add all the gauges to one single program
and then choose which to add (according to plane name or
manually) but I don't think is a good idea to have a lot of
instruments in the same program.
Making an instrument-panel.exe for each plane on the
other hand, requires more work, especially when something
has to be updated.
I will experiment different solutions.
Inserting one simple L:var required a lot of work, probably
this could be made simpler, L vars are widely used in many
planes!

Best regards

Massimo



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Privo
di virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno sab 3 mag 2025 alle ore 08:12 Scott Vincent <
***@***.***> ha scritto:
