### ISSUE TITLE
Instruments disappear on second monitor

### ISSUE THREAD

**Issue by Jbtmike** [scott-vincent/instrument-panel#52]
Hello Scott,
I just discovered instrument-panel and it's really great! Thank you so much !
However, I'm facing a problem that I can't solve.
MSFS2020 runs on a laptop (windows 11) and I put a second monitor via hdmi to display the instruments.
when I run instrument-panel 1.7.4 (without modifying your configuration files) on the laptop screen everything works fine and I can see the instruments clearly.
When I switch instrument-panel to the second monitor (with the "m" key) the instruments disappear and I only see the instrument-panel version number (1.7.4....).
I can't figure out what I'm doing wrong.
I have the same problem whatever the version of instrument-panel.
Is there a particular monitor configuration (color, freq, ...)?
I call you for help!
Thanks in advance
Jbtmike

**Comment by Jbtmike** [comment]
Hello Scott,
Find a particular freq problem with my monitor. Now it's ok !

**Comment by scott-vincent** [comment]
Glad you got it sorted

**Comment by alfawalidou** [comment]
Hello Scott
Is there a way to make it work on X-Plane12 ?
thank you

Le sam. 25 mars 2023 à 10:38, Scott Vincent ***@***.***> a
écrit :
