### ISSUE TITLE
Alternate pi?

### ISSUE THREAD

**Issue by sonjamichelle** [scott-vincent/instrument-panel#53]
I was able to successfully run instrument panel on a pi4 and 10 inch touch screen. Very fluid, though I did notice that when ATC gave me a squawk code, the radio panel still stayed at 1200. Not sure if the "assisted ai" changes the squawk or not. I never really payed attention in MSFS. My flight time has been limited the past couple of years, but5 now that I have time again I am getting back in with a fervor. 

My ultimate goal is to run a G1000 setup which looks like it would be beyond the scope of this application. However I was thinking this could be a great alternative to run on an 8 or 12 inch screen that are commonly used for pc stats with Aida64. The goal would be to replicate the ["Six Pack"](https://www.mcico.com/resources/flight-instruments/six-pack-aircraft-instruments-explained) of backup instruments.

Would I have to use a pi4, which are either impossible to get or you have to trade in your first born as payment? I do have a handful of pi zero w boards from an old motioneye project. Could I compile the source to run on the zero for the smaller subset of instruments?

I have sources for G1000 apps and several 3D printers to mount the displays and electronics for the buttons/dials. Right now I am using Air Manager 4 with a PopOut instrument and touch button overlay on the 10 inch screens. It is a bit kludgy since PopOut performance on MSFS isn't the greatest at the moment. It is a known issue from what I understand, but seems that it is low on the totem pole compared to other fixes and addons.

**Comment by scott-vincent** [comment]
I use a number of Pi zero w's for driving other stuff that doesn't need a display and is only 7-segment display hardware, buttons and leds. One for the autopilot, one for the radio and one for my power/lights panel. I find the instrument panel definitely needs a Pi 4 as it requires the processing power and also it uses OpenGL 3.0 ES which I found only works well on the Pi 4. For the G1000 I also just pop it out and display it on a tablet using Spacedesk (connected to the PC via USB).

**Comment by sonjamichelle** [comment]
I have the Saitek Radio Panel, works great for my radios. My AP Panel's digit display died, so a pi zero to run an new AP panel might be in order.

Pi 4's are getting waaaaay too over priced these days, IF you can even find them. (damn scalpers). So I'm assuming any clone (orange pi, banana pi) would work as long as it can run debian and the required libs. I do have a [banana pi m3](https://www.banana-pi.org/en/banana-pi-sbcs/51.html). STILL close to the original price of a pi4 on [Ali](https://www.aliexpress.us/item/3256803494210783.html?pdp_npi=3%40dis%21USD%21US%20%2494.74%21US%20%2447.37%21%21%21%21%21%402103228816830403411965926e3be3%2112000026781071282%21sh01%21US%213742770117&spm=a2g0o.store_pc_home.productList_2005308574890.subject_7&gatewayAdapt=vnm2usa&_randl_shipto=US). Beats the near $200USB that you can find the pi4 these days.

The banana pi [lineup on Ali](https://www.aliexpress.com/store/1101951077).

My experiences with SpaceDesk has been mixed. I keep installing/uninstalling it. I just haven't really settled on an option for it. Maybe it's time to revisit it.

I did order a [3.5 inch lcd and arduino mega combo](https://www.aliexpress.us/item/2251832494557878.html?spm=a2g0o.order_list.order_list_main.5.75051802UvMvgf&gatewayAdapt=glo2usa&_randl_shipto=US) from Ali that I'm looking at making one or two GNS430 units or even 530 if the 430 works well. (Gotta get a square LCD for that and print out some new mounts then.  :-)  )

I'll play around with the Cessna panel on my old beat up pi4 (sd card broke off, booting from usb now. It's had a rough life, hehe). If all goes well, maybe I'll dedicate it to an 8 inch rectangular (or even 12) for my "six pack". Mounts those on the [VolairSim](https://volairsim.com/) just below the G1000 screens. I don't use a yoke anymore. I use an X-Box controller. It is easier to use these days with my tremor and neuropathy. Less crashing and I don't need to turn on assistance, other than the floating guidelines.

I ALMOST have MSFS2020 fully installed and calibrated. Just finishes getting all my AI packages installed, got all my add-ons, settling in on the "array" of ancillary apps I want to run (littlenavmap, RealTraffic, datalink, AirManager, REX Weather Force, FSUIPC and a couple of other little apps).  I'm new to overclocking, trying to squeeze out a bit more performance on the beast pc. Right now I'm just trying to find the balance between OC and Temp. Just about dialed in. I may have to set up some auxiliary cooling. My workshop tends to get warm in the summers, the A/C unit is a bit small for the space. 

I do have my own FlightSim dedicated website. Kind of bare at the moment. I'll document my projects there. (https://www.sonjas-hangar.us/)

If you have suggestions on any other panel/gauge projects that I may be interested in, please let men know. I don't want to go full blown Home Cockpit, but I would like a nice instrument panel setup.  ;-) I like touching real buttons and switches and not mousing around on the screen.

**Comment by sonjamichelle** [comment]
I started modifying the json for my six-pack panel, well it turned into an eight-pack panel because of the size of the LCD I chose.

The resolution of the screen is 1480x320.

My json so far:

`
{
  "Data Link": {
    "Host": "192.168.1.101",
    "Port": 52020,
    "Data Rate FPS": 20
  },
  "Monitor": {
    "StartOn": 0,
    "Fullscreen": true,
    "Width": 1480,
    "Height": 320,
    "PositionX": 0,
    "PositionY": 0
  },
    "ASI": {
    "Enabled": true,
    "Position X": -150,
    "Position Y": 50,
    "Size": 500
  },
    "TC": {
    "Enabled": true,
    "Position X": 360
    "Position Y": 50,
    "Size": 500
  },
  "ALT": {
    "Enabled": true,
    "Position X": 880,
    "Position Y": 50,
    "Size": 500
  },
  "ADI": {
    "Enabled": true,
    "Position X": 1420,
    "Position Y": 50,
    "Size":500
  },
}

`

The negative value of the ASI was just so I can test fit the gauges on a 10 inch LCD I had. I'll get the 1480x320 LCD screens next payday (Being on a retirement income kinda sucks these days, lol)

So far the panel is working nice and smooth. I can't wait until I have the "eight pack" complete.

![Gauge_Size_Test_sm](https://user-images.githubusercontent.com/8279771/236217342-eeeaa5d5-0309-4b27-941a-8f5cfd6f9368.jpg)

A crappy one handed video showing the gauges in motion.

[https://youtu.be/OzOR1Lw3h-0](url)

**Comment by scott-vincent** [comment]
Looking good. I love my instrument panel. Been using it nearly every day for the last 2 years. I mostly fly either the FBW A320neo or the Cessna 152. Currently doing my virtual PPL on Vatsim UK.

**Comment by sonjamichelle** [comment]
Is there a list of variables for the sim? I want to assign some switches to batt,alt, avi 1 and 2. Sort of a heads up visual of the switch. I have all 4 functions assigned to two physical switches on the Bravo at the moment. I want to make a dedicated physical switch panel for them once I get a better idea of the physical layout on my VolairSim.

I'm assuming it is in the MSFS SDK, though they really don't make it simple to download,, lol. Not everything has to be done from within the simulator.  ;-)

**Comment by scott-vincent** [comment]
https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Simulation_Variables.htm

**Comment by sonjamichelle** [comment]
Awesome!, Thank you.

I keep forgetting that their website is pretty in depth these days.

**Comment by sonjamichelle** [comment]
My test with the banana pi M3 didn't go well. It had issues with the banana pi implementation of WiringPi. Kept complaining that is saw an allwinner chip rather than broadcom.

I have a raspberry pi 4b 8gb. Fortunately it has 2 HDMI ports. I want to use it with two LCDs. Right now it is working great with the two "test" LCDs I have. I plan on getting a couple of 11.9inch Capacitive Touch Displays with 320x1480 resolution. On top of those will go the printed bezels and backplane.

I have the the instrument panel directory copied (intrument_panel_1 and  instrument_panel_2). When I start ip in full screen mode it is sometimes a "crap shoot" on what screen it will choose. At least for me so far. If I run ip "windowed" I can drag it where I need it to be. Is there a way to specify the monitor?

Also, is there a way to disable the screen-saver feature of ip? I find it hard to see the panel when designing a panel and I don't need/want to have FS open.

**Comment by duceduc** [comment]
@sonjamichelle Hi. I am also using a 10.1 rpi monitor. Would you mind sharing your instruction-panel.json file?

**Comment by sonjamichelle** [comment]
@duceduc I would if I could but I lost all my files to a hard drve failure a while back. Haven't even been simming for a while now. time and my health and just the right pain in the ass MSFS has been to install with any stability has soured me for a while on the Sim. I mainly just fire up theX-Box if I get an ith to fly aa bit these days. Right now i've got my hands full with some 3D printing projecs and helping my Wife with her business.

BUT!! If you look up  a few posts to the one I did on MAY 4th 2023 that MIGHT be the json you are looking for.

IF in fact by instruction-panel you meant instrument-panel. If so, did you read the posts or just look at the pretty pictures? If you read the posts, then that is the json you are looking for young Skywalker (Yes, that is a May the 4th pun, lol)

**Comment by duceduc** [comment]
Yea. I've spent an hour or so after I figured out what the codes were doing. This is what I have so far. The nav radio freq is a bit small, but I think I have captured all the instruments.

![IMG_0410](https://github.com/user-attachments/assets/b0665d5c-9809-411d-a61a-4a59bd1c3849)

**Comment by sonjamichelle** [comment]
As I said, I haven't the system set up for many months now, so I can't really troubleshoot.

Buy it LOOKS like everything is there.

As for the NAV being small, try changing this parameter:  "Size": 500     I can't say or recall if that gauge will scale properly or not, but it can't hurt to change the number to see, then change back if not.
