### ISSUE TITLE
Lag when instrument panel is in background window.

### ISSUE THREAD

**Issue by ChandlerHooley** [scott-vincent/instrument-panel#55]
I am using the TDS Sim GTN750xi unit on one monitor, flight sim on another, and the instrument panel on another. When I am using my GTN, it uses the mouse to click and makes the instrument panel not the highlighted window. I have noticed that it begins to be really jumpy when it does this, maybe 2-3 FPS if I had to guess.

I am new to using this software so I may be doing something wrong, if I am please let me know. 

Thanks for all the work you are doing on this amazing project!!

**Comment by scott-vincent** [comment]
Yes, I think this is one of the limitations of running it on the same PC. My instrument panel runs on a separate Raspberry Pi so I don't have this problem.

**Comment by ChandlerHooley** [comment]
Okay. Makes sense. I can do that but is there any way to reduce latency in using the Pi? I know it's not bad but just curious
