### ISSUE TITLE
Heading bug moving by 5° instead of 1°

### ISSUE THREAD

**Issue by SteevieSky** [scott-vincent/instrument-panel#57]
Hi, thanks for your great add on to FS2020. When turning the heading bug, the move is 1° in FS2020 but on the instrument panel, only moving after 5°. Any chance to update the move to 1° for the heading bug on the instrument panel ? or did I miss something ? many thanks

**Comment by scott-vincent** [comment]
If you're using an encoder then clicking it toggles between 5° increments and 1° increments.

**Comment by SteevieSky** [comment]
Thanks for your quick reply. I am using 2 buttons from my joystick to increase or decrease the heading bug which is done by 1° in FS2020 but by 5° on the instrument panel. How can I get to switch from the 5° increment which is by default I suppose to 1° increment on the instrument panel ? thanks in advance

**Comment by scott-vincent** [comment]
The code that does it in 5° increments is at  line179 of hi.cpp:

int adjust = ((int)(val - prevVal) / 2) * 5;

You would have to remove the * 5 if you wanted it in 1° increments.

**Comment by SteevieSky** [comment]
Many thanks for pointing me in the right path. I am not a programmer so will ask a friend for assistance to do the mod. Thanks for your time helping me.
