### ISSUE TITLE
MacOs release

### ISSUE THREAD

**Issue by yanghu** [scott-vincent/instrument-panel#6]
Is it possible to release instrument panel for Mac OS? (since allergo5 also supports macos)?

**Comment by scott-vincent** [comment]
Yes, of course it is. Once I get enough donations I'll buy a Mac and build it for you.

**Comment by yanghu** [comment]
Thanks for your reply! I was just curious if it's possible.(If the code has other dependencies that are hard to setup on Mac). 
I'll try to figure it out and maybe send a pull request.
