### ISSUE TITLE
when building, make.sh cannot find simvars.h file

### ISSUE THREAD

**Issue by alexandergrib** [scott-vincent/instrument-panel#8]
Just pulled fresh files from repository
run bash make.sh

and i get lots of messages simvars.h no such file or directory.

also can you build raspberry image, so we can just copy to sd card and use without trouble installing it.

**Comment by scott-vincent** [comment]
Do you have simvars.h on your filesystem. Sounds like it is missing! You
may have cloned the repository incorrectly.
Why don't you use the pre-built Raspberry Pi version if you're not sure how
to build it?

**Comment by alexandergrib** [comment]
I do have simvars in the folder.
Prebuild one wont start saying filed to initialize allegro. I have allegro installed.

**Comment by kkr0kk** [comment]
Raspi zero W, DEBIAN buster up to date, i have the same error when i start the pre-built release version -> failed to initialize allegro

**Comment by scott-vincent** [comment]
This software should be run on a Raspberry Pi 4 as stated in the Readme. I think you're wasting your time trying to get it to run on anything less powerful, it needs to update every instrument 30 times a second. The Pi 4 has hardware accelerated OpenGL and supports OpenGL ES 3.2 which is what I've configured Allegro to use.

**Comment by alexandergrib** [comment]
I use Raspberry 4B Model 2, with 4GB memory. And i get that error.  Can you create image with everything preinstalled?
That would solve many problems.

Also i can see liballegro5 in my installed apps(with apt list --installed).

**Comment by crossfader1337** [comment]
Hi there, I´m having the same issue (failed to initialize allegro) on a Rasberry 4/4GB.

**Comment by scott-vincent** [comment]
Try the Black Screen fix listed in Known Issues in the Readme. Also, try some of the sample programs that come with Allegro5 and make sure they work.

**Comment by crossfader1337** [comment]
Caught in a loop :D I wasn´t able to get the ready made versions to work. However I compiled instrument panel and data link (in vs) from the github repo and finally both show up and connect. But now I´m stuck with the black screen despite all mentioned fixes :)

**Comment by scott-vincent** [comment]
Black screen issue is now fixed.
